/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#6ffbbe",
        "on-primary-fixed": "#001d31",
        "surface": "#faf8ff",
        "on-tertiary-container": "#f5fff6",
        "outline": "#707881",
        "on-secondary": "#ffffff",
        "background": "#faf8ff",
        "tertiary-container": "#00855b",
        "secondary-container": "#86f2e4",
        "surface-container-highest": "#dae2fd",
        "secondary-fixed-dim": "#6bd8cb",
        "on-surface-variant": "#3f4850",
        "on-tertiary-fixed": "#002113",
        "on-background": "#131b2e",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#005236",
        "primary-container": "#007bb9",
        "error-container": "#ffdad6",
        "on-surface": "#131b2e",
        "inverse-primary": "#93ccff",
        "secondary": "#006a61",
        "on-primary": "#ffffff",
        "secondary-fixed": "#89f5e7",
        "surface-bright": "#faf8ff",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#4edea3",
        "surface-tint": "#006398",
        "on-secondary-container": "#006f66",
        "on-secondary-fixed-variant": "#005049",
        "surface-container": "#eaedff",
        "on-secondary-fixed": "#00201d",
        "surface-container-high": "#e2e7ff",
        "tertiary": "#006947",
        "outline-variant": "#bfc7d2",
        "inverse-surface": "#283044",
        "surface-dim": "#d2d9f4",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#eef0ff",
        "on-error-container": "#93000a",
        "primary": "#006194",
        "surface-container-low": "#f2f3ff",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#cce5ff",
        "surface-variant": "#dae2fd",
        "on-primary-container": "#fdfcff",
        "primary-fixed-dim": "#93ccff",
        "on-primary-fixed-variant": "#004b73"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "page-pad-desktop": "2.5rem",
        "space-2xs": "0.25rem",
        "space-2xl": "2.5rem",
        "page-pad-mobile": "1.25rem",
        "space-3xl": "3rem",
        "space-xl": "2rem",
        "gutter-desktop": "1.5rem",
        "gutter-mobile": "1rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem"
      },
      fontFamily: {
        "telemetry-value-md": ["Plus Jakarta Sans", "sans-serif"],
        "telemetry-value-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "label-caps": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-hero": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "telemetry-value-md": ["32px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "telemetry-value-lg": ["48px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-hero-mobile": ["38px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "700" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "600" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
