const mongoose = require('mongoose');

/**
 * AQIHistory — aggregated daily analytics data used by the Analytics page.
 *
 * One document per day per device. Contains KPI summaries, compliance
 * breakdowns, gas matrix readings (morning/afternoon/night), and
 * anomaly events recorded that day.
 *
 * In a real system this would be generated by a nightly aggregation job
 * over raw SensorReading documents. For now, the seed populates 7 days
 * of historical data.
 */
const aqiHistorySchema = new mongoose.Schema(
  {
    device: { type: mongoose.Schema.Types.ObjectId, ref: 'Device', required: true },
    date:   { type: Date, required: true },

    // KPI summary for the day
    avgBaseline:     { type: String },
    purityRating:    { type: String },
    purityBreakdown: {
      good:  { type: String },
      mod:   { type: String },
      spike: { type: String },
    },
    purifierRuntime: { type: String },         // total hours
    runtimeBreakdown: {
      purge: { type: String },
      eco:   { type: String },
      idle:  { type: String },
    },
    fanModulation:     { type: String },
    powerConsumption:  { type: String },       // kWh
    powerCost:         { type: String },       // USD
    mitigatedMass:     { type: String },       // grams

    // AI Diagnostic summary
    timeSavedMins: { type: String },

    // AQI Trends
    peakSpikeResponse: { type: String },       // minutes
    meanAirClearance:  { type: String },       // minutes
    diurnalStability:  { type: String },

    // Compliance breakdown (%)
    goodPercent:      { type: Number },
    goodHrs:          { type: Number },
    modPercent:       { type: Number },
    modHrs:           { type: Number },
    sensitivePercent: { type: Number },
    sensitiveHrs:     { type: Number },

    // Gas matrix (three time slots)
    gasMatrix: {
      morning:   { eco2: String, tvoc: String, drift: String },
      afternoon: { eco2: String, tvoc: String, drift: String },
      night:     { eco2: String, tvoc: String, drift: String },
    },

    // Anomaly events recorded this day
    anomalies: [
      {
        timestamp:        { type: String },
        location:         { type: String },
        trigger:          { type: String },
        triggerColor:     { type: String },
        description:      { type: String },
        peakAqi:          { type: Number },
        remediationMode:  { type: String },
        remediationColor: { type: String },
        duration:         { type: String },
        resolutionAqi:    { type: Number },
      },
    ],
  },
  { timestamps: true }
);

aqiHistorySchema.index({ device: 1, date: -1 });

module.exports = mongoose.model('AQIHistory', aqiHistorySchema);
